### ISSUE TITLE
Contextmenu dynamic items causes 'undefined is not a function'

### ISSUE THREAD

**Issue by JaroVDH** [ritesh83/ember-cli-jstree#22]
If the context menu is defined like this, it will break with the error 'undefined is not a function':
```
options: {
  "show_at_node": false,
  "items": function(node){
    return {
     "option1": {"label": "Option 1", "action": "someAction", disabled:node.data.isDisabled?true:false}
    };
  }
}
```

with stacktrace:

```
Uncaught TypeError: undefined is not a function
$.vakata.context._execute @ jstree.js:5852
(anonymous function) @ jstree.js:6058
jQuery.event.dispatch @ jquery.js:4670
jQuery.event.add.elemData.handle @ jquery.js:4338
```

This works (for the most part, at the very least it sends the action, but 1.13 issue stops it there):
```
options: {
  "show_at_node": false,
  "items": {
       "option1":{"label": "Option 1", "action": "someAction"}
  }
}
```

This might be related to #17 . I got most of the tree working in Ember 1.13.7, except for the context menu actions.

**Comment by ritesh83** [comment]
Should work now.
